package com.cricket.platform.tournament;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Positive;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;
import java.time.LocalDate;
import java.util.*;

@RestController
@RequestMapping("/api/tournaments")
public class TournamentController {
 private final JdbcTemplate jdbc; public TournamentController(JdbcTemplate jdbc){this.jdbc=jdbc;}
 @GetMapping("/mine") List<TournamentView> mine(Authentication a){UUID o=ownerId(a);return jdbc.query("SELECT id,name,format,overs,location,start_date,status,created_at FROM tournaments WHERE owner_id=? ORDER BY created_at DESC",(r,n)->new TournamentView(r.getObject("id",UUID.class),r.getString("name"),r.getString("format"),r.getInt("overs"),r.getString("location"),r.getObject("start_date",LocalDate.class),r.getString("status"),r.getObject("created_at").toString()),o);}
 @PostMapping TournamentView create(@Valid @RequestBody CreateRequest q,Authentication a){UUID o=ownerId(a),id=UUID.randomUUID();jdbc.update("INSERT INTO tournaments(id,name,format,overs,location,start_date,status,owner_id) VALUES (?,?,?,?,?,?,?,?)",id,q.name().trim(),q.format().trim().toUpperCase(Locale.ROOT),q.overs(),blank(q.location()),q.startDate(),"DRAFT",o);return get(id,a);}
 @GetMapping("/{id}") TournamentView get(@PathVariable UUID id,Authentication a){requireOwner(id,a);return jdbc.queryForObject("SELECT id,name,format,overs,location,start_date,status,created_at FROM tournaments WHERE id=?",(r,n)->new TournamentView(r.getObject("id",UUID.class),r.getString("name"),r.getString("format"),r.getInt("overs"),r.getString("location"),r.getObject("start_date",LocalDate.class),r.getString("status"),r.getObject("created_at").toString()),id);}
 @GetMapping("/{id}/teams") List<TeamView> teams(@PathVariable UUID id,Authentication a){requireOwner(id,a);return jdbc.query("SELECT t.id,t.name,t.city,tt.seed FROM tournament_teams tt JOIN teams t ON t.id=tt.team_id WHERE tt.tournament_id=? ORDER BY COALESCE(tt.seed,999),t.name",(r,n)->new TeamView(r.getObject("id",UUID.class),r.getString("name"),r.getString("city"),r.getObject("seed",Integer.class)),id);}
 @PostMapping("/{id}/teams/{teamId}") TeamView addTeam(@PathVariable UUID id,@PathVariable UUID teamId,Authentication a){requireOwner(id,a);requireTeamOwner(teamId,a);try{jdbc.update("INSERT INTO tournament_teams(tournament_id,team_id,seed) VALUES (?,?,(SELECT COALESCE(MAX(seed),0)+1 FROM tournament_teams WHERE tournament_id=?))",id,teamId,id);}catch(DataIntegrityViolationException e){throw new ResponseStatusException(HttpStatus.CONFLICT,"Team is already added to this tournament");}return jdbc.queryForObject("SELECT t.id,t.name,t.city,tt.seed FROM tournament_teams tt JOIN teams t ON t.id=tt.team_id WHERE tt.tournament_id=? AND tt.team_id=?",(r,n)->new TeamView(r.getObject("id",UUID.class),r.getString("name"),r.getString("city"),r.getObject("seed",Integer.class)),id,teamId);}
 @DeleteMapping("/{id}/teams/{teamId}") void removeTeam(@PathVariable UUID id,@PathVariable UUID teamId,Authentication a){requireOwner(id,a);jdbc.update("DELETE FROM tournament_teams WHERE tournament_id=? AND team_id=?",id,teamId);}
 @PostMapping("/{id}/matches/{matchId}") FixtureView addMatch(@PathVariable UUID id,@PathVariable UUID matchId,@RequestParam(defaultValue="LEAGUE") String stage,Authentication a){requireOwner(id,a);Integer ok=jdbc.queryForObject("SELECT COUNT(*) FROM matches m JOIN tournament_teams x ON x.tournament_id=? AND x.team_id=m.team_a_id JOIN tournament_teams y ON y.tournament_id=? AND y.team_id=m.team_b_id WHERE m.id=?",Integer.class,id,id,matchId);if(ok==null||ok==0)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Both match teams must belong to the tournament");try{jdbc.update("INSERT INTO tournament_matches(tournament_id,match_id,stage,fixture_number) VALUES (?,?,?,(SELECT COALESCE(MAX(fixture_number),0)+1 FROM tournament_matches WHERE tournament_id=?))",id,matchId,stage.toUpperCase(Locale.ROOT),id);}catch(DataIntegrityViolationException e){throw new ResponseStatusException(HttpStatus.CONFLICT,"Match is already linked to a tournament");}return fixture(id,matchId);}
 @GetMapping("/{id}/fixtures") List<FixtureView> fixtures(@PathVariable UUID id,Authentication a){requireOwner(id,a);return jdbc.query("SELECT tm.match_id,tm.fixture_number,tm.stage,m.name,m.team_a_id,x.name team_a_name,m.team_b_id,y.name team_b_name,m.status,m.scheduled_at FROM tournament_matches tm JOIN matches m ON m.id=tm.match_id JOIN teams x ON x.id=m.team_a_id JOIN teams y ON y.id=m.team_b_id WHERE tm.tournament_id=? ORDER BY COALESCE(tm.fixture_number,999999),m.scheduled_at NULLS LAST",(r,n)->new FixtureView(r.getObject("match_id",UUID.class),r.getObject("fixture_number",Integer.class),r.getString("stage"),r.getString("name"),r.getObject("team_a_id",UUID.class),r.getString("team_a_name"),r.getObject("team_b_id",UUID.class),r.getString("team_b_name"),r.getString("status"),r.getObject("scheduled_at")==null?null:r.getObject("scheduled_at").toString()),id);}
 @GetMapping("/{id}/points-table") List<PointRow> points(@PathVariable UUID id,Authentication a){requireOwner(id,a);List<PointRow> out=new ArrayList<>();for(TeamView t:teams(id,a)){int p=0,w=0,l=0,ti=0,rf=0,ra=0;double bf=0,ba=0;List<MatchScore> ms=jdbc.query("SELECT m.id,m.team_a_id,m.team_b_id,ia.total_runs ar,ia.legal_balls ab,ib.total_runs br,ib.legal_balls bb FROM tournament_matches tm JOIN matches m ON m.id=tm.match_id LEFT JOIN innings ia ON ia.match_id=m.id AND ia.innings_number=1 LEFT JOIN innings ib ON ib.match_id=m.id AND ib.innings_number=2 WHERE tm.tournament_id=? AND m.status='COMPLETED' AND (m.team_a_id=? OR m.team_b_id=?)",(r,n)->new MatchScore(r.getObject("id",UUID.class),r.getObject("team_a_id",UUID.class),r.getObject("team_b_id",UUID.class),r.getInt("ar"),r.getInt("ab"),r.getInt("br"),r.getInt("bb")),id,t.id(),t.id());for(MatchScore m:ms){p++;boolean isA=t.id().equals(m.a());int own=isA?m.ar():m.br(),opp=isA?m.br():m.ar(),ob=isA?m.ab():m.bb(),pb=isA?m.bb():m.ab();rf+=own;ra+=opp;bf+=ob;ba+=pb;if(own>opp)w++;else if(own<opp)l++;else ti++;}double nrr=bf>0&&ba>0?(rf/(bf/6.0))-(ra/(ba/6.0)):0;out.add(new PointRow(t.id(),t.name(),p,w,l,ti,w*2+ti,rf,ra,Math.round(nrr*1000.0)/1000.0));}out.sort(Comparator.comparingInt(PointRow::points).reversed().thenComparing(Comparator.comparingDouble(PointRow::nrr).reversed()).thenComparing(Comparator.comparingInt(PointRow::runsFor).reversed()));return out;}
 private FixtureView fixture(UUID tid,UUID mid){return jdbc.queryForObject("SELECT tm.match_id,tm.fixture_number,tm.stage,m.name,m.team_a_id,x.name team_a_name,m.team_b_id,y.name team_b_name,m.status,m.scheduled_at FROM tournament_matches tm JOIN matches m ON m.id=tm.match_id JOIN teams x ON x.id=m.team_a_id JOIN teams y ON y.id=m.team_b_id WHERE tm.tournament_id=? AND tm.match_id=?",(r,n)->new FixtureView(r.getObject("match_id",UUID.class),r.getObject("fixture_number",Integer.class),r.getString("stage"),r.getString("name"),r.getObject("team_a_id",UUID.class),r.getString("team_a_name"),r.getObject("team_b_id",UUID.class),r.getString("team_b_name"),r.getString("status"),r.getObject("scheduled_at")==null?null:r.getObject("scheduled_at").toString()),tid,mid);}
 private UUID ownerId(Authentication a){try{return jdbc.queryForObject("SELECT id FROM users WHERE LOWER(TRIM(email))=LOWER(TRIM(?)) OR CAST(id AS TEXT)=?",UUID.class,a.getName(),a.getName());}catch(Exception e){throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"User not found");}}
 private void requireOwner(UUID id,Authentication a){Integer n=jdbc.queryForObject("SELECT COUNT(*) FROM tournaments WHERE id=? AND owner_id=?",Integer.class,id,ownerId(a));if(n==null||n==0)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Tournament not found");}
 private void requireTeamOwner(UUID id,Authentication a){Integer n=jdbc.queryForObject("SELECT COUNT(*) FROM teams WHERE id=? AND owner_id=?",Integer.class,id,ownerId(a));if(n==null||n==0)throw new ResponseStatusException(HttpStatus.FORBIDDEN,"You do not manage this team");}
 private static String blank(String s){return s==null||s.isBlank()?null:s.trim();}
 public record CreateRequest(@NotBlank String name,@NotBlank String format,@Positive int overs,String location,LocalDate startDate){}
 public record TournamentView(UUID id,String name,String format,int overs,String location,LocalDate startDate,String status,String createdAt){}
 public record TeamView(UUID id,String name,String city,Integer seed){}
 public record FixtureView(UUID matchId,Integer fixtureNumber,String stage,String matchName,UUID teamAId,String teamAName,UUID teamBId,String teamBName,String status,String scheduledAt){}
 public record PointRow(UUID teamId,String teamName,int played,int wins,int losses,int ties,int points,int runsFor,int runsAgainst,double nrr){}
 private record MatchScore(UUID id,UUID a,UUID b,int ar,int ab,int br,int bb){}
}
